<?php

use Perspective\Partytown\Block\Config;

/** @var Config $block */

// Configuration
$configJson = $block->getConfigJson();
?>

<script>
	const partytownConfig = <?= $configJson ?> || {};
	const { 
		debug, 
		debugModes, 
		forward, 
		loadScriptsOnMainThread, 
		isProxyingEnabled, 
		proxyUrl, 
		proxyingRequestDomains,
		lib
	} = partytownConfig;

	const debugModesObj = Array.isArray(debugModes) ? debugModes.reduce((a, v) => ({ ...a, [v]: true }), {}) : {};

	window.partytown = {
		lib,
	    loadScriptsOnMainThread,
	    forward,
	    debug,
	    ...debugModesObj,
	};

	if (isProxyingEnabled) {
	    window.partytown.resolveUrl = function (url, location, type) {
	        if (proxyingRequestDomains.includes(url.hostname)) {
	            let proxyUrl = new URL(proxyUrl);
	            proxyUrl.searchParams.append("url", url.href);
	            return proxyUrl;
	        }
	        return url;
	    };
	}
</script>
