<?php

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Perspective\Partytown\ViewModel\PartytownConfig;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var $viewModel PartytownConfig */

$viewModel = $block->getViewModel();
$configJson = $viewModel->getConfigJson();
?>

<script>
    const partytownConfig = <?= $configJson ?> || {};
    const {
        debug,
        debugModes,
        forward,
        isProxyingEnabled,
        lib
    } = partytownConfig;

    const debugModesObj = Array.isArray(debugModes) ? debugModes.reduce((a, v) => ({ ...a, [v]: true }), {}) : {};

    window.partytown = {
        lib,
        forward,
        debug,
        ...debugModesObj,
    };

    let loadScriptsOnMainThread;
    if(partytownConfig?.loadScriptsOnMainThread){
        loadScriptsOnMainThread = partytownConfig.loadScriptsOnMainThread;
        window.partytown.loadScriptsOnMainThread = loadScriptsOnMainThread;
    }


    if (isProxyingEnabled) {
        window.partytown.resolveUrl = function (url, location, type) {
            const proxyingRequestDomains = <?= $viewModel->getProxyingRequestDomains() ?? 0 ?> || [];
            let proxyUrl = "<?= (string) $viewModel->getProxyUrl() ?>";
            if (proxyingRequestDomains.includes(url.hostname)) {
                proxyUrl = new URL(proxyUrl);
                proxyUrl.searchParams.append("url", url.href);
                return proxyUrl;
            }
            return url;
        };
    }
</script>
