<?php
$isEnabled = $block->isEnabled(); 
if (!$isEnabled) { 
	return; 
}

$forwardingEventsList = $block->getForwardingEventsList();
$isProxyingRequestsEnabled = $block->isProxyingRequestsEnabled();
$proxyRequestsDomains = $block->getProxyingRequestList(); 
$proxyUrl =$block->getProxyUrl(); 
$debugMode = $block->isDebugEnabled();

?>

<?= $block->getChildHtml('js-core') ?>

<script>
	const forward = <?= $forwardingEventsList ?>;
	const debug = !!<?= $debugMode ?> || false;
    partytown = {
    	<?php if ($isProxyingRequestsEnabled && $proxyRequestsDomains): ?>
    		resolveUrl: function (url, location, type) {
			  const proxyRequestsDomains = <?= $proxyRequestsDomains ?>;
    		  if(proxyRequestsDomains.includes(url.hostname)){
				let proxyUrl = new URL(`<?= (string) $proxyUrl ?>`);
    		    proxyUrl.searchParams.append('url', url.href);
    		    return proxyUrl;
    		  }
    		  return url;
    		},
    	<?php endif; ?>
    	forward,
    	debug
    }
</script>
